// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOcGBX4bv_L1g5xhGiKwOynRAbRFqAYA',
    appId: '1:1022938722350:web:812d63698d328e52606fbf',
    messagingSenderId: '1022938722350',
    projectId: 'task-hamsa',
    authDomain: 'task-hamsa.firebaseapp.com',
    storageBucket: 'task-hamsa.firebasestorage.app',
    measurementId: 'G-B97DC0KQ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAf1m9Fo4uLfbTJLqvykkO2sNJGiVMcpM',
    appId: '1:1022938722350:android:c13f4efa199e7ada606fbf',
    messagingSenderId: '1022938722350',
    projectId: 'task-hamsa',
    storageBucket: 'task-hamsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sVO4YBIKCpDHNufhHBpwhn2LYBipePo',
    appId: '1:1022938722350:ios:e52603bb5ac670da606fbf',
    messagingSenderId: '1022938722350',
    projectId: 'task-hamsa',
    storageBucket: 'task-hamsa.firebasestorage.app',
    iosBundleId: 'com.hamsa.taskHamsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sVO4YBIKCpDHNufhHBpwhn2LYBipePo',
    appId: '1:1022938722350:ios:e52603bb5ac670da606fbf',
    messagingSenderId: '1022938722350',
    projectId: 'task-hamsa',
    storageBucket: 'task-hamsa.firebasestorage.app',
    iosBundleId: 'com.hamsa.taskHamsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKOcGBX4bv_L1g5xhGiKwOynRAbRFqAYA',
    appId: '1:1022938722350:web:51e2e9e92c48a0b0606fbf',
    messagingSenderId: '1022938722350',
    projectId: 'task-hamsa',
    authDomain: 'task-hamsa.firebaseapp.com',
    storageBucket: 'task-hamsa.firebasestorage.app',
    measurementId: 'G-K2KKYYS0SV',
  );
}
